### ISSUE TITLE
Unable to get API keys working

### ISSUE THREAD

**Issue by CreateSean** [doublesecretagency/craft-googlemaps#101]
I am unable to get the API keys working - I've followed the instructions from the docs and I keep getting errors when testing.

Have deleted keys and re-created 3 times but no success. Does not work locally or on production server.

Please advise

![image](https://github.com/doublesecretagency/craft-googlemaps/assets/6899490/0fe0c8e3-d3c6-4780-9d79-20f6b8e9a6d1)

**Comment by lindseydiloreto** [comment]
Hi @CreateSean,

It's tough to say exactly what the issue is, but clearly the API keys are not valid in Google's eyes. The Server Key message would typically indicate if it were a billing error.

If I had to guess (which is basically what I'm doing), I'd say that your "Application Restrictions" are invalid...

https://plugins.doublesecretagency.com/google-maps/getting-started/api-keys/#the-difference

<img width="557" src="https://github.com/doublesecretagency/craft-googlemaps/assets/5309692/3c35a33b-e200-4628-8456-54b2953a86bf">

Make sure you've restricted those keys to the correct domain(s) and IP address, respectively.

Hope that helps! If you're still stuck, ping me on Discord and we can discuss in greater detail. 👍
