### ISSUE TITLE
Connection refused for MaxMind URI 

### ISSUE THREAD

**Issue by br-designer** [doublesecretagency/craft-googlemaps#114]
We're getting an error with the Visitor Geolocation Service using MaxMind's GeoIP2 City. We noticed the error on August 2nd. I've attached a screenshot of the error. I can navigate directly to the URL and enter our User ID & License Key, which returns a result. 

craftcms/cms: 4.10.6
doublesecretagency/craft-googlemaps: 4.5.2

<img width="884" alt="Screenshot 2024-08-07 at 9 33 47 AM" src="https://github.com/user-attachments/assets/02c198e3-6b56-445d-aeb7-b6d171122f7b">

**Comment by lindseydiloreto** [comment]
Hey Kyle, sorry for the late reply! Did you ever get this ironed out?

Since no one else reported this issue, I'm guessing it's probably a configuration issue with your MaxMind credentials. Triple-check to make sure everything is correct.

If you're still hitting this issue, feel free to ping me on Discord and we can walk through it together!

**Comment by br-designer** [comment]
Hey Lindsey, completely forgot about this. After about two weeks it resolved itself. Definitely an issue with Maxmind since we didn't make any changes. I'll close this out!

**Comment by lindseydiloreto** [comment]
Ok great, thanks for closing the loop on this! 👍
