### ISSUE TITLE
Migration Error - "Cannot change column 'siteId'"

### ISSUE THREAD

**Issue by Selvavinoth1** [doublesecretagency/craft-googlemaps#125]
When upgrading to 4.6.0 from 4.5.2 I get a migration error which causes the update to fail and for the map to go down:

Database Exception: SQLSTATE[HY000]: General error: 1832 Cannot change column 'siteId': used in a foreign key constraint 'fk_jbvdpkpyvhghqzxcpgwetxfwrrckrlmohabe'

The only way to clear this is to revert that database and the composer.json / composer.lock files.

This on Craft 4.13.5

**Comment by lindseydiloreto** [comment]
Thanks for reporting, this is the exact same issue as #124 (with the exact same title, in fact).

Please follow that thread for a pending solution.

**Comment by lindseydiloreto** [comment]
I stand corrected, this is a very subtly different issue. I was thrown off by the fact that you copied 90% of the other ticket and pasted it here. In the future, you may want to make more of an effort to show that your issue is in fact unique.

Can you please send me an export of your database, plus both composer files? You can either find me on Discord, or send an email to support/doublesecretagency/com.

**Comment by Selva-infotex** [comment]
Hi @lindseydiloreto,

Thanks for your reply, 

Yes, I have differentiated the error which was reported from the other issue. This issue was encountered after updating from version 4.5.2 to 4.6.0, as mentioned previously. Additionally, the Craft CMS version is 4.13.5, as noted in the initial report.

Additionally, we will check internally and provide you with the database and composer file shortly.

**Comment by Selvavinoth1** [comment]
Hi @lindseydiloreto,

Thanks for your reply,

Yes, I have differentiated the error which was reported from the other issue. This issue was encountered after updating from version 4.5.2 to 4.6.0, as mentioned previously. Additionally, the Craft CMS version is 4.13.5, as noted in the initial report.

Additionally, we will check internally and provide you with the database and composer file shortly.

**Comment by Selva-infotex** [comment]
Hi @lindseydiloreto, 

Could you please clarify if you require the full database or just the craft-googlemaps table?

Providing the full database raises data privacy concerns, so we would prefer to share only the craft-googlemaps table if that is sufficient for your investigation. Please confirm.

**Comment by Selvavinoth1** [comment]
Hi @lindseydiloreto,

Could you please clarify if you require the full database or just the craft-googlemaps table?

Providing the full database raises data privacy concerns, so we would prefer to share only the craft-googlemaps table if that is sufficient for your investigation. Please confirm.

**Comment by lindseydiloreto** [comment]
Having only the `googlemaps_addresses` table may provide some insights, but I'd probably have trouble solving the problem with just that table.

The OP of #124 is now experiencing this same bug (because that one is fixed). They may be willing to provide me with  complete database export, hopefully that will be enough to resolve the issue.

**Comment by lindseydiloreto** [comment]
Actually, I _may_ have just been able to fix it blind. Grab the latest `dev` release and give it another shot...

```js
"doublesecretagency/craft-googlemaps": "dev-v4-dev"
```

Make sure you've rolled back the database before trying the migration again.

Let me know how it goes! 🤞

**Comment by lindseydiloreto** [comment]
Great news, this patch has been officially released in [v4.6.1](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.6.1). 🎉

If you've experienced a failed migration, be sure to roll the database back before trying again.

Hope that helps, thanks again for reporting!

**Comment by Selvavinoth1** [comment]
Hi @lindseydiloreto,

Thanks for the fixes. We have applied the latest version to the website and the plugin migration is completed but unfornately, we're getting this error on the respective page where the googlemap plugin is intergrated. Attached the error message and screenshot, please check and let us know. 

Key "siteId" is not a column name and can not be used as a filter

![image](https://github.com/user-attachments/assets/8ab9932f-b42c-439b-97e7-e5242f6676fc)

**Comment by lindseydiloreto** [comment]
Hi @Selvavinoth1, are you still experiencing this issue?

If so, can you please start a separate Github thread for it?

**Comment by Selva-infotex** [comment]
This issue is resolved, and it can be closed.
