### ISSUE TITLE
How to perform proximity searches on related elements?

### ISSUE THREAD

**Issue by aaronbushnell** [doublesecretagency/craft-googlemaps#38]
We have a unique setup in that we have **Buildings** and **Locations**. Our building entries house the Google Map field and many locations can exist _within_ the building. Here's the schema:
```
BUILDING
- Title
- Address (Google Maps)

LOCATION:
- Title
- Building (Entries; single select relationship)
```

Because of this setup I cannot perform a proximity search on "Locations" as the Google Map field doesn't exist on this entry type:
```twig
{% set params = { 'target': 'chicago', radius: 100 } %}

{% set locations = craft.entries.section('location').address(params).orderBy('distance').all() %}
```

Any recommendations on the best way to achieve this type of proximity search where the address field exists on a _related_ entry? 

Thanks!

**Comment by lindseydiloreto** [comment]
I'd recommend running the proximity search on the **Buildings** section directly, since that's where the Address field is.

Then work backwards from there...

```twig
{# Get all buildings, sorted by distance #}
{% set buildings = craft.entries.section('building').address(params).orderBy('distance').all() %}

{# Loop through results #}
{% for building in buildings %}

    {# Get each building location #}
    {% set location = craft.entries.relatedTo(building).one() %}

    {# ... then whatever you want #}

{% endfor %}
```

I admit it may get a little interesting with multiple Buildings sharing the same Location. You may need to do some fancy juggling of Twig data to minimize any repetitive DB queries.

Hope that helps! Feel free to hit me up on Discord if you get stuck on the details. 🙂

**Comment by aaronbushnell** [comment]
Thanks, @lindseydiloreto!
