### ISSUE TITLE
Map Field address not updating pin - also latitude/longitude grayed out

### ISSUE THREAD

**Issue by CreateSean** [doublesecretagency/craft-googlemaps#46]
Craft 3.7.34
Google Maps 4.1.1

I upgraded a client site, from smart map to google maps, a few weeks ago and all seemed good on the front end.

Today discovered that adding an address to the field does not update the pin. Additionally the Latitude, Longitude and Zoom fields are grayed out.

Moving the pin on the map works but that is not precise enough.

![image](https://user-images.githubusercontent.com/6899490/159332574-2f7b1a92-b5d6-48f9-a29e-6707ffd1c097.png)

**Comment by lindseydiloreto** [comment]
The greyed out coordinates is a [new feature](https://plugins.doublesecretagency.com/google-maps/address-field/settings/#display-coordinates)... they can be set to "Read Only" (the default). Feel free to edit the field settings and enable those fields entirely if you'd like.

The coordinates fields should be automatically filled when you select an address from the Google Places API results. Check out this animated GIF which demonstrates the expected behavior...

https://plugins.doublesecretagency.com/google-maps/address-field/

If you're still having trouble, DM me on Discord and I can help you sort it out! 👍
