### ISSUE TITLE
Craft CMS 3.x Compatibility

### ISSUE THREAD

**Issue by RitterKnightCreative** [doublesecretagency/craft-googlemaps#76]
Is Craft 3.x still supported?

Looking at the changelog, as of 4.2, with the addition of Craft 4 compatibility, it has locked out 3.x from any updates.  

I would understand if new features didn't make it to the 3.x branch but it would be nice if bug fixes made their way back  - eg the [Console](https://github.com/doublesecretagency/craft-googlemaps/commit/fdfef82bd3b1a2a2fe8d5f01da1d765823432f86#diff-d5802ad727560df5f52b7749a4fae026dfbc923ebb815f0a95525a20ad785fbf]) error was fixed in the 3.x branch.

**Comment by lindseydiloreto** [comment]
Hi @RitterKnightCreative, good question. Technically yes, a Craft 3 compatible version of the plugin (v4.1.x) is still supported for _critical security and stability issues_. Unfortunately, I don't think this bug falls under either category.

The error message that you are seeing is [actually harmless](https://stackoverflow.com/a/75212692/3467557). It's a visual nuisance, but has no legitimate impact. I probably won't bother backporting the fix for it, unless I need to backport something else simultaneously.

I can leave this thread open in case the fix ever gets backported. Sorry, hopefully you can update to Craft 4 soon!

**Comment by RitterKnightCreative** [comment]
I find that response disappointing, especially seeing as this is a paid plugin and how easy this is to fix. (We patched it in about 5 minutes.) I ran into the console error after debugging some other issue which his how I found out about it.

"Harmless" or not, an error message—caused by YOUR plugin not doing something it's *supposed* to be doing in the first place—caused this, not our client's lack of upgrading to Craft 4.  You even gave a very detailed answer about how to fix this on StackOverflow so it clearly mattered EXCEPT when it comes to supporting paying customers, so I'm curious what is driving the lack of motivation to fix this now?

What happens when Google decides to not show a map at all at some point because they decide any thrown error?

**Comment by lindseydiloreto** [comment]
You offer a harsh critique of our support services, which we believe are among the best in the Craft ecosystem. As you’re well aware, we (Double Secret Agency) have many other responsibilities and obligations, including a dozen other plugins, client work, and the Work With Craft website. I’m sure you would agree that many of these other properties are also in need of our attention. We must pick our battles, and backporting this cosmetic fix to Craft 3 did not immediately make the cut. Sorry.

> What happens when Google decides to not show a map at all at some point because they decide any thrown error?

If this were to happen, it would escalate this bug from "annoying console message" to an _actual_ stability issue. In which case, we would happily backport the fix for it.

Seems pretty unlikely though. Google has not enforced that requirement at all for many years, and has only very recently begun "enforcing" it in the loosest possible way. Before becoming a "required" parameter, `callback` was an optional parameter for around 7 years. If this were to become a hard requirement overnight, it would break tens (maybe hundreds) of thousands of sites... with no real benefit to Google.

For what it’s worth, Craft 3 itself has [less than two months of full support remaining](https://craftcms.com/knowledge-base/supported-versions). I'm not telling you to update because of our plugin, but our plugin will pretty soon be the least of your concerns.

I’m sorry that this answer is disappointing to you, I’m glad you were able to patch it quickly on your personal fork. Again, this is a purely cosmetic issue, strictly relegated to the developer console. It has absolutely no real bearing on any functionality whatsoever. If you’re still bothered by this decision, feel free to hit me up on Discord, where you can express your displeasure in greater detail.
